language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.3
    - nightly

# codecov: true
# coveralls: true

notifications:
    email: false

before_install:
    # If it is linux, we must install `libncurses`.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --reinstall libncurses5     libncursesw5;     fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --reinstall libncurses5-dev libncursesw5-dev; fi

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
